{% set name = "minio" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f96d7f461ff88d7df2932eecf55f955ed93874c7ed84bc9454b2d7955de768fe

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - urllib3
    - pytz
    - certifi
    - python-dateutil
    - configparser

test:
  imports:
    - minio
    - minio.api
    - minio.helpers
    - minio.error
    - minio.sse
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/minio/minio-py
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: MinIO Python Library for Amazon S3 Compatible Cloud Storage for Python

  description: |
    The MinIO Python Client SDK provides simple APIs to access any Amazon S3
    compatible object storage server.
  doc_url: https://docs.min.io/docs/python-client-api-reference
  dev_url: https://github.com/minio/minio-py

extra:
  recipe-maintainers:
    - tjd2002
    - guzman-raphael
