{% set name = "minio" %}
{% set version = "4.0.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35643f056b4d12e053fa7d8f40d98394ed7cc4d5d44ba53c9971e7428fd58e60

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - urllib3
    - pytz
    - certifi
    - python-dateutil

test:
  imports:
    - minio
    - minio.api
    - minio.helpers
    - minio.error
    - minio.sse
    
about:
  home: https://github.com/minio/minio-py
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'MinIO Python Library for Amazon S3 Compatible Cloud Storage for Python'

  description: |
    The MinIO Python Client SDK provides simple APIs to access any Amazon S3
    compatible object storage server.
  doc_url: https://docs.min.io/docs/python-client-api-reference
  dev_url: https://github.com/minio/minio-py

extra:
  recipe-maintainers:
    - tjd2002
    - guzman-raphael
