travis:
  secure:
    BINSTAR_TOKEN: i/xBJzKDpap069agiI0XEuXOS4HkxbbFST+FdYrZ2gvwn4474Vv72L2Ctlxyq13NhvnKEV+neoNZOpmftc/4dnA6PXKFiUMk2b9bG8Eaie7CZNCGlBfu2L88iBDc797DGsJYK//bIfKFOhWzXvfTj3NnmZdL25buPV5AhUWTeEJwFyf+UmLIJmY562Z1v/+HeDkYna130897s0fnVZFTJ7npFzAyTUS2C7sokRuRHMGzEa0j219UeTrF1hJXTUYgKQ+91awV58Kr7tMmUJjzoZoQaMOC+wqvM4FJxKBG49IMSiB1mgIy0UKbE/js2DmZ89ZiMiaduKMJ7/Uvfqry+WvRwhfjnQKhIyRrQOrptFx74q30Nzzv0sa6QftwEsZicvoXVBZecr6vGXZzpBdc7DL77v5eoVgJgSNEtH/9UwMGUUcRLjjYaIZ8RSAwrAOpBpGO8UiSo04Hjsn/GLI/IozuPgrN2y5SyatU5zxJVEVAmhv1kbbwMo5s/H/OQeNl7qe5UKIDPMdVIc56sGdRhClXudajODlVIGgU+5xStqKchtDmLtcBdO0PtSTnLOe2iAb2HCuJK05SriHuJ92qDJABJiiBVzoLr3vBtpGIt2Sc3YAx9rPXeAvU6eDtalxO3+fnhC4uLlhD6zmo9ElxeHzEaY31iEorga+P3MFPO/I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
